### ISSUE TITLE
can you please explain more details about the data?

### ISSUE THREAD

**Issue by jason887** [benwu232/train_hard#1]
hi, I download the data, the validate_data shape is (333981, 1, 2, 128), i know 333981 is sample size, can you explain what is the (2,128),thanks

**Comment by benwu232** [comment]
Sure! Thanks for the question!

I use 128 days data. The first row is close price and the second row is volume. The equation new_v = log(1+v) is applied to the volume row to make it smoother. The common normalization(subtracted by mean and divided by standard division) algorithm is applied in each row to make them 0 mean and symmetric.

I also add this to the readme.

Any question, please let me know.
