### ISSUE TITLE
binary classification get all 02 with GRU

### ISSUE THREAD

**Issue by jason887** [benwu232/train_hard#2]
i am studying Chinese stock market with  binary classification with GRU, the traing samples is balance and the output is fine with class 1s and 0s, however, when i want to predict the real data, almost all  return is all 0s.
 It is very strange the i have one mode can predict 2 classes with oneday, the predict output is similar to training data, which is fine.
when this mode that can get 2 classed  is trained with more epoches, I try to use it to predict the same day data, it's predict data is all like 0.2-0.3, which means I get all 0s?
I prepare all real data with same code, why
Any idea?thanks

**Comment by benwu232** [comment]
Not sure. What are 0s and 1s mean? I plan to try RNN models later, because they are more complex. What do you mean the mode can predict 2 classes with one day? Does it predict both 0 and 1 for the same data?
